### ISSUE TITLE
Connection state and partition info

### ISSUE THREAD

**Issue by greendale1924** [Azure/azure-event-hubs-java#118]
Hello,

I would like to ask you if it is possible to get some state information out of the EventProcessorHost at any time during runtime (and when it is impossible, are there any plans for exposing the info?). I need the following information:
- All partitions of the hub (the names).
- All leased partitions by my instance.
- (In case that this is different from the previous one) All leased partition on which the instance is actively listening.
- In case the processor is listening to 0 partitions, is it because all are leased by somebody else, or there are network or other problems on connecting to the storage and/or to the hub.

Would you recommend other ways of doing this, e.g. evaluating the content of the storage manually?

**Comment by JamesBirdsall** [comment]
Item (1) is available in the latest version via EventHubClient.getRuntimeInformation.

The other items all boil down to the same thing: what is the state of each partition? Leased by this instance and receiving OK/leased by this instance but there was an error receiving/leased by another instance/state unknown due to storage errors/etc. We have some of that information today and could expose it, but due to race conditions the information can be stale and misleading. For example, host instance A can believe that it still owns the lease on partition 0 and is receiving from it even when host instance B has stolen the lease and started receiving -- A doesn't know that the state has changed until it receives notice that its receiver has been forcibly disconnected, which can take some time.

Can you describe what you're trying to achieve by looking at this information?

**Comment by greendale1924** [comment]
Thanks for your answer!

Here is my use case:
I will have M instances of my application and the hub will have N
partitions. I need to query my instances for monitoring purposes. The most
important thing is to check that all partitions have active listeners, so
there are no pending messages just staying on the hub. (When I use a JMS
listener, I can check if at least one consumer is connected to the queue.
So I need something similar.) The other thing is to check how the
partitions are spread among the instances when M<>N.

So, did you mean that for now it is impossible to get the lease information?

**Comment by JamesBirdsall** [comment]
As far as I can tell, no version of Event Processor Host exposes the detailed information you're looking for, including the .NET Framework version that has been around for years. That one comes closest, but even then you can only get information about partitions where the EPH instance owns the lease and the information is only available when a message batch comes in.

This is a feature that we could add, but so far there hasn't been customer demand for it. I believe most customers do monitoring via getRuntimeInformation/getPartitionRuntimeInformation, which is a very different model but allows you to check your last known processed sequence number versus the last enqueued sequence number.

**Comment by JamesBirdsall** [comment]
The best option currently available for monitoring this state is to put instrumentation in your implementations of IEventProcessor.onOpen and IEventProcessor.onClose. That will let you track what partitions are owned by each instance of EventProcessorHost.

**Comment by greendale1924** [comment]
The problem with IEventProcessor.onOpen is that it is called before the actual "opening" and there is no callback that tells me "you are now successfully connected to that partition" (THIS WOULD BE GREAT).
This forces me to do some interpretations of the exception in IEventProcessor.onError (because IEventProcessor.onClose is not always called in case of an error). This is a workaround and can work only for the cases that I have seen and handle now.
