### ISSUE TITLE
Missing EventHubClient.getRuntimeInfo()

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#14]
_From @hmlam on February 9, 2016 14:4_

per title. customer need this just like the .Net version.

_Copied from original issue: Azure/azure-event-hubs#34_

**Comment by SreeramGarlapati** [comment]
This is work in progress: 
if anyone is looking for interim solution - refer to this test:
`https://github.com/Azure/azure-event-hubs-java/blob/master/azure-eventhubs/src/test/java/com/microsoft/azure/eventhubs/sendrecv/RequestResponseTest.java`

**Comment by SreeramGarlapati** [comment]
tagging @dluc - who is interested in this..

**Comment by dluc** [comment]
Thanks @SreeramGarlapati, yes we're looking forward to have this API available

**Comment by DuoyueBa** [comment]
Could you tell us the schedule for this implementation?

**Comment by wwwlucatoit** [comment]
@DuoyueBa the implementation is available, I've been using it already 👍

**Comment by dluc** [comment]
@DuoyueBa the feature is available in the latest version 👍

**Comment by SreeramGarlapati** [comment]
@DuoyueBa - we released an equivalent feature as part of 0.12.0.
Instead of making a separate API call (to GetPartitionRuntimeInfo) to EventHubs, we implemented an optimization where the runtimeInfo is available on the Receiver. Please go thru the release notes of 0.12.0:
https://github.com/Azure/azure-event-hubs-java/releases/tag/0.12.0
