### ISSUE TITLE
Tutorial EventProcessorHost constructor does not support event hubs with underscores in name

### ISSUE THREAD

**Issue by JamesHutchison** [Azure/azure-event-hubs-java#144]
This is by following the tutorial referenced here:
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-receive-eph#comments-container

## Actual Behavior
1. Target an event hub with an underscore in the name, using the `EventProcessorHost` constructor defined in the tutorial
2. Call `host.registerEventProcessor`
3. Get com.microsoft.azure.storage.StorageException: The specifed resource name contains invalid characters.

## Expected Behavior
1. tutorial works as expected

## Versions  
- OS platform and version: Mac OS X el capitan 10.11.2
- Maven package version or commit ID: azure-eventhubs and azure-eventhubs-eph 0.14.2

The workaround is to manually specify the storage container name but it seems this would be very confusing to someone just trying to consume from their event hub using the tutorial.

```
        EventProcessorHost host = new EventProcessorHost(
            EventProcessorHost.createHostName(null), eventHubName, consumerGroupName,
            eventHubConnectionString.toString(), storageConnectionString, 
            eventHubName.replace('_', '-'), "", null
        );
```

**Comment by JamesBirdsall** [comment]
Thanks for bringing this up. By default we use the event hub name as the storage container name so users can more easily find the EPH-related storage artifacts for their event hubs if they ever need to. But when that fails because the rules for event hub names and storage container names are different, the experience is very bad, as you point out.

Changing the way we generate the default storage container name is a delicate operation because of all the existing instances which might no longer find their existing storage artifacts after upgrading EPH versions. One possible option is to recognize when an event hub name does not meet the storage container name rules and generate the storage container name differently only in that case -- because we know that anyone who is using EPH with such an event hub now MUST be providing a container name manually, so they will be unaffected by changes to the default storage container name generation algorithm.

**Comment by JamesHutchison** [comment]
If you replace all of the invalid characters with something valid you don't really have to check if the name is invalid beforehand, since they would be unaffected. Of course then you have to worry about name collisions.

Maybe it would be better if the tutorial used this constructor:
```
public EventProcessorHost(String hostName, String eventHubPath, String consumerGroupName, String eventHubConnectionString, String storageConnectionString, String storageContainerName)
```

Since it would give an opportunity to explain what the purpose of hostName and storageContainerName are, which are used in all of the non-deprecated constructors. The existing (deprecated) constructor seems to simply be saving the user the burden of plugging in arbitrary strings.

**Comment by JamesBirdsall** [comment]
This is a moot point now because as of the 1.0 release EventProcessorHost does not automatically generate storage container names anymore, in part due to issues like this. All constructors require the user to supply a storage container name.
