### ISSUE TITLE
Regression: EventProcessorHost leaves mutiple threads running

### ISSUE THREAD

**Issue by greendale1924** [Azure/azure-event-hubs-java#175]
Using the sample EventProcessorSample from https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-receive-eph

## Actual Behavior
1. The sample program never exits: Even after the main method returns, there are multiple daemon and pool threads staying alive.

## Expected Behavior
1. The sample program exits

## Versions  
- Using azure-eventhubs-eph:0.13.1, everything is fine
- Using azure-eventhubs-eph:0.14.0 or azure-eventhubs-eph:0.14.4 - the problem occurs

**Comment by vinipuh5** [comment]
The bug exists in 0.15.1 too.

**Comment by jimaldous** [comment]
This actually a significant issue affecting my use of Event Hubs. It isn't very "elastic" to scale up instances in an event group if they hang when being stopped. Any word on the relative priority of this issue or a timeframe for when it will be addressed?

**Comment by JamesBirdsall** [comment]
This issue is being addressed as part of the internal refactoring for #134 which changes how the thread pool is used and gets rid of the long-running EPH threads. We don't have a definite time frame but we are aware that customers are waiting for this and other issues addressed in the refactoring and we would like to get the next release out soon. With the holidays, "soon" is probably sometime in January.

**Comment by jimaldous** [comment]
While it is still "sometime in January", is there any update on this issue? :)

**Comment by JamesBirdsall** [comment]
The new release has acquired a dependency on a new service feature, which has pushed the release date out to mid-February. The bulk of the EPH changes landed in dev branch with PR#202 if you want to take a look.

**Comment by JamesBirdsall** [comment]
PR#202 was merged and has become part of the 1.0 release.
