### ISSUE TITLE
EventHub Client creation during network outage results in unclosed resources (Threads). Depending on how this client is created (see below for details) this leak causes system crash and thus impacts availability of our services.

### ISSUE THREAD

**Issue by yingting2017** [Azure/azure-event-hubs-java#186]
We embed the EventHub Client com.microsoft.azure:azure-eventhubs version 0.14.3 in our services and libraries, during a test to emulate network outage we found that the EventHub  Client creation code i.e. EventHubClient.createFromConnectionStringSync(connectionString)results in zombie threads, causing a spike in the thread count on the JVM. We were creating the event hub client from the static create method and upon failure we re-attempt to create a new client at regular intervals. The reason for this approach is that network partitions/drops are transient and thus will be recovered by, so when the network partitioning resolves itself the client should be able to connect and reestablish connections and send messages.
 
The issue we noted was that the EventHubClient constructor internally calls MessagingFactory.createFromConnection method which in turn uses an asynchronous model to create a Reactor instance on a thread. That reactor instance initializes a connection to the EventHub asynchronously and the MessagingFactory.createFromConnection essentially awaits the completion of the creation on messagingFactory.open (it awaits on a Future). 
 
We found that if network connectivity is lost, the messagingFactory.open call fails with a TimeoutException which goes unhandled and gets thrown all the way back out of EventHubClient.createFromConnectionStringSync as a ServiceBusException.This results in the invoker receiving a ServiceBusException but the thread created internally for the Reactor does not get closed/terminated and thus keeps spinning.
 
If in any instance, the code tries to create new clients repetitively it adds to the churn of creating new threads and eventually the JVM crashes. We have seen thread dumps resulting in a couple 100 threads being spun

**Comment by SreeramGarlapati** [comment]
Hi @yingting2017 - Thanks a lot for reporting the issue. This is a good one - we missed it.

Our usual outage test is to **test our runtime API's**.
Since, creation of `EventHubClient` is done only once and what the Application really does when an outage happens is to Send/Receive - we focused on `EventHubClient.send(...)` and `PartitionReceiver.receive(...)` for outage situations and missed this :).
Our `runtime` APIs retry internally (as per the `RetryPolicy` set) and will communicate proper exceptions to the Application consuming our API.

Feel free to try out those APIs in your tests - while we work on fixing this bug.

**Comment by Toupin** [comment]
Hi, similar problem here...

In my case, we are using EventProcessorHost to consume the event-hubs. Description:
1- We create an EPH and while trying to register the EventProcessorFactory an exception is thrown due to our proxy blocking the communication.
2- Our managment of the incidence is to unregister the EPH and retry EPH creation after 5 minutes.

So we are in a loop trying to create an EPH each five minutes and leaving new zombieThreads.

If we open the access through the proxy, the EPH is created correctly. But...
we have created a MessageProcessor that notifies if there is a problem processing an event that demands stoping the events consummer from the event-hubs (e.g. an outage of our internal database where we store part of the events). In such situation we again try to unrgister al EPH's to recreate all of them after 5 minutes. It's a loop while the internal resource outage. And in this case library is leaving zombie threads too. I think its's related to issue #113 

I'm wondering if It's wrong our aproximation to EPH use and failure managment?

**Comment by SreeramGarlapati** [comment]
@yingting2017 & @Toupin - can you please try the change #192 and see if this fixes your issue!?

**Comment by SreeramGarlapati** [comment]
#192  is merged to master.
