### ISSUE TITLE
Enhancement / Feature wish: Query size of partition back pressure

### ISSUE THREAD

**Issue by theoDiefenthal** [Azure/azure-event-hubs-java#267]
For certain usecases (i.e. mainly monitoring), it is important to know about the size of the back pressure in the EventHub. The Azure dashboard is not capable of showing the number of events between a consumer group (partition) position and the current event in a partition, likely because it doesn't know about the storage of the consumer pointers. 

I don't know much about the internals of the Azure Event Hubs Java SDK, but I think, it should (somehow) be possible to query the EventHub for the latest event on a dedicated partition and find the difference such that the number of not yet received messages can be determined.

**Comment by JamesBirdsall** [comment]
This feature already exists: please look at the PartitionReceiver.getRuntimeInformation method. Each time the service transfers an event down the wire to the client, it includes information on the latest event enqueued in that partition. You can compare the sequence number or enqueue time from getRuntimeInformation to those of the event you are currently processing to get an idea of how big the backlog is for that partition.

Because the information is only updated when the service transfers an event to the client, it could be somewhat stale, but you can check ReceiverRuntimeInformation.getRetrievalTime to determine if and how stale it might be.
