### ISSUE TITLE
IEventProcessor does not allow asynchronous propagation of backpressure

### ISSUE THREAD

**Issue by jroper** [Azure/azure-event-hubs-java#351]
The `IEventProcessor.onEvents` method does not allow asynchronous propagation of backpressure:

```java
public void onEvents(PartitionContext context, Iterable<EventData> events) throws Exception;
```

Since the method has a `void` return type, and no way to asynchronously signal the event host to backoff, the only way that a `IEventProcessor` can ensure that it does not get overwhelmed with new events when it's not read to receive them is to block the thread that invoked `onEvents`.

In order to support asynchronous propagation of backpressure, this method should have a `CompletionStage<Void>` return type, allowing the the processor to asynchronously redeem the `CompletionStage` when it is ready to receive more events (and of course, the thing that invokes it must also respect that). Of course, that will break binary compatibility, but there are multiple ways that this could be worked around, for example, the following changes could be made:

```java
default void onEvents(PartitionContext context, Iterable<EventData> events) throws Exception {
  // Do nothing by default
}
default CompletionStage<Void> onEventsAsync(PartitionContext context,
  Iterable<EventData> events) throws Exception {
  onEvents(context, events);
  return CompletableFuture.completedFuture(null);
}
```

In the above, implementors may either implement `onEvents` or `onEventsAsync`, depending on whether they want to asynchronously process the events or not.

**Comment by markthegrea** [comment]
Hey!  This would be great!  

Currently in the NiFi ConsumeAzureEventHub processor, backpressure does not work.  It just keeps sending more events into the queue.  If we are millions behind it would never quit and the server could run out of memory.

See the below code base.  While the codebase is simple, the lack of back pressure could cause us not to use EHubs in the future as Kafka does not have this problem (I assume).

[https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/eventhub/ConsumeAzureEventHub.java](url)

**Comment by JamesBirdsall** [comment]
It sounds like the desire here is to have receiver behavior affect senders? This is not a concept that Event Hubs has. An Event Hub receiver does not "consume" events in the sense that is common for queues or topics: the events are still there in Hub until they are purged by the retention time limit, and a client application can go back and revisit those events as many times as desired. That's why Event Processor Host needs the checkpoint concept on the client side, to keep track of which events the client app has seen, because the Hub itself is just an ordered bag of events and does not know or care whether a given event has been retrieved, or by which client, or how many times.

As such, the only thing onEvents has to care about is whether it itself is done with the current batch of events and is ready to handle more, which it signals by returning.

Backpressure, in this sense, implies that event producers can block if the consumers get too far behind. Event Hubs is intended for scenarios where the producers can't block and is by design the buffer which enables them to not block but instead to simply send and let the consumers worry about keeping up. If the consumers can't keep up, it's time to create an event hub with more partitions, to allow spreading the load across more consumers in parallel.

If I have misinterpreted the question, please let me know!

**Comment by jroper** [comment]
Hi @JamesBirdsall, yes you have misunderstood. You are right in saying:

> As such, the only thing onEvents has to care about is whether it itself is done with the current batch of events and is ready to handle more, which it signals by returning.

That's where the problem is, the only way to signal that it's done with the current batch is by returning, which means it must block the current thread until it is finished, meaning it can only do blocking IO, it can't do any non blocking operations.

If it instead returned a CompletionStatement, then it can signal completing the current batch by redeeming the CompletionStage, allowing it to start some non blocking operation, and return from onEvents immediately even though it hasn't yet finished handling the current batch.

**Comment by JamesBirdsall** [comment]
onEvents internally is welcome to do async operations and achieve whatever level of parallelism the application allows for. We only ask that it doesn't return until that processing is complete -- and if the application uses checkpointing, it should do that wait, THEN checkpoint, THEN wait for checkpointing to be complete, and only then return, to really be reliable.

An onEventsAsync could line all that work up as series of CompletionStages and return the last one, but then the pump would have to do block and wait, and it's not clear what the advantage is. The block and wait has to happen somewhere. We cannot issue multiple concurrent onEvents calls because checkpointing depends on ordering.

**Comment by jroper** [comment]
I'm not familiar with the EventHubs client implementation and transport protocol, but I know Kafka's is pull based. If EventHubs is the same, then it should be a simple matter of not doing the next pull until the returned completion stage completes. Nothing has to block on anything. So simplistically, the code would look like this:

```java
private void pullAndHandleNextEvents() {
  CompletionStage<Iterable<EventData>> eventsFuture = pullNextEvents();
  CompletionStage<Void> result = eventsFuture.thenComposeAsync(
    events -> eventProcessor.onEvents(context, events),
    executor
  );
  result.thenRunAsync(this::pullAndHandleNextEvents, executor);
}
```

There's no blocking there, no threads are waiting for anything to happen, and it guarantees that `onEvents` is called one at a time, waiting till the completion stage it returns is redeemed before invoking it again.

**Comment by JamesBirdsall** [comment]
AMQP is a push protocol and the handler-oriented approach of EventHubs clients reflect that. The part of EventProcessorHost which calls IEventProcessor.onEvents is itself an onEvents handler that is called by the underlying EventHubs client according to the same rules. If it returns, it will get called again with a new batch. The only tool it has to prevent concurrent batch processing is to block and wait for the current batch to be finished.

It would be possible to rip that out and replace it with a receive "loop" based on CompletionStages, but that is a major change and it is not clear what value that provides to the application developer.

**Comment by jroper** [comment]
Whether the protocol is push or pull is orthogonal to whether an application propagates backpressure using threads or signals. If you can push back by blocking a thread, you can push back by sending an asynchronous signal (which redeeming a completion stage is), they are just implementation details, there is nothing fundamental about a push protocol that changes whether it must be implemented using blocking or non blocking IO.

So, if the protocol is push, then the solution is to push back on the TCP connection while the application is not interested in receiving more events. On top of the Java NIO APIs, this would mean deregistering read interest from the channel, and reregistering read interest when the completion stage is redeemed. That's a very low level detail and usually you'd have multiple layers in between, but that's essentially what happens.

The value that this provides to the application developer is that it allows them to use a reactive programming model to integrate with EventHubs. This came up for me when I was implementing support for EventHubs in MicroProfile Reactive Messaging:

https://github.com/jroper/microprofile-reactive-messaging/tree/eventhubs

In order to implement it, I have to block the thread until elements are consumed, and aside from the obvious excess resource usage because it means you have threads consuming stack space doing nothing while they are blocked (the general argument for using non blocking over blocking IO), it's also dangerous because combining blocking and non blocking operations can lead to dead locks, particularly if the executor invoking `onEvents` is the same executor that also handles the check pointing.

**Comment by JamesBirdsall** [comment]
Thank you for sticking with this discussion; I think we are finally getting to be on the same page.

AMQP does have a flow-control mechanism, known as credit, and the EventHubs client uses it. It's not directly exposed to the user, but EPH in its current form exposes it indirectly: the client issues more credit to the service, which allows more events to flow down the wire, as events are consumed, and the user controls that by not returning until they're ready for another batch. Prior to this, we haven't seen demand for a different model.

Your point about deadlocks is well-taken because EPH has recently encountered exactly the problem you describe, after a threading change down in the client, and there will be a 2.0.1 release soon to deal with it. In that light, the changes required to support your scenario will have wider benefits as well and are worth considering for 2.1.

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. We will not be making major changes. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs -- the new client is structured sufficiently differently that I don't know if this issue applies, but feel free to reopen it there if you want to check.
