### ISSUE TITLE
[Question] Thread safety of IEventProcessor

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#368]
According to comments of `IEventProcessor`:
> Although EventProcessorHost is multithreaded, calls to a given instance of an event processor class are serialized, except for onError().

Does that mean `onEvents()` from the same partition will be called from same thread? Then we don't need to handle thread safety in `onEvents()` implementation?

**Comment by JamesBirdsall** [comment]
onEvents calls are thread-safe in the sense that they are serialized: onEvents will never be called again while a previous call is still in progress. From a Java VM point if view, it may not be the same thread from call to call, but because of the serialization you do not have to worry about concurrency. For example, if your onEvents implementation updates some data structure in a non-atomic way, you don't need to protect that data structure against multiple onEvents calls trying to update at the same time.

**Comment by shubhambhattar** [comment]
Hi @JamesBirdsall , thanks for your response. I just want to clarify something.

When you say calls to `onEvents()` are **thread-safe** in the sense that they are serialized, you mean method calls are **synchronized**, right? As in if different threads call a particular instance of EventProcessor's `onEvents()`, then the calls will queue up if the current execution isn't over?

**Comment by JamesBirdsall** [comment]
It's not a matter of synchronization or queuing, exactly. What's happening underneath is this: for each partition, down in the low-level client there is a receive "loop" which uses an epoch receiver to consume messages from that partition. When the receive call completes, it calls a handler in the Event Processor Host library using the thread that handled the completion. Event Processor Host in turn calls IEventProcessor.onEvents using that same thread. onEvents does whatever it does and eventually returns to the handler in Event Processor Host, which in turn does some housekeeping and returns to the receive "loop" in low-level client, which ends the iteration by making another receive call. Each iteration through the "loop" happens on a single thread that is fired off when a receive call completes, and the next receive call is made by that thread, so there's no way to get more than one onEvents call at a time.

Note that this explanation is about onEvents calls for one partition. If you're using the default IEventProcessor factory, then there is one IEventProcessor instance per partition and instances will not see concurrent onEvents calls. If you are using a factory implementation that returns the same instance for multiple partitions, then that instance can see concurrent onEvents calls because each partition has a separate "loop".

What about performance? Wouldn't making another receive call immediately result in higher throughput by fetching messages while onEvents runs? The key here is that AMQP is not a request-response protocol. It is a streaming protocol, and the service streams messages down to the client whenever they are available. There is a chunk of the low-level client which operates asynchronously from the application as a whole, responding to packets arriving on the network and putting messages into a buffer -- effectively, any time there is space in the buffer, the client will be trying to get messages from the service. The receive call mentioned above actually consumes from that buffer, not the service directly, so making it in parallel with onEvents would complicate the code without actually retrieving messages from the service any faster.
