### ISSUE TITLE
[Question] Best practice of size of ExecutorService when constructing EventProcessorHost

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#369]
Questions as below:
1. How should we size this `ExecutorService`? Should the size be equal the number of partition divides the number of hosts?
2. What's the purpose of this `ExecutorService`? Is this only used for receiving the message? or also doing checkpoint?

**Comment by JamesBirdsall** [comment]
The ExecutorService is used for almost all operations within EPH, including both receiving and doing checkpoints. If you don't supply one, EPH will create a default one, which currently has 16 threads. That seems to work well for the majority of cases. For large event hubs, such as 64 partitions or higher, a larger thread pool might help. It is hard to provide definite recommendations because IEventProcessor.onEvents also runs in this thread pool, and the performance and complexity of the user's code can affect how many threads are available to do other work. In general, if event processing seems slow, trying an ExecutorService with a larger number of threads available is an easy experiment.
