### ISSUE TITLE
TimeoutExceptions

### ISSUE THREAD

**Issue by JRiggenbach** [Azure/azure-event-hubs-java#370]
## Actual Behavior
Occassional TimeoutExceptions being thrown after long period of time of stability.   We don't believe this to be an issue with the application/sdk or the event hub itself, but was curious if there was some additional troubleshooting steps that could be recommended?  Also, do the REFERENCE_ID and LINK_CREDIT fields in the error context provide any clues?

`
com.microsoft.azure.servicebus.TimeoutException: Send operation timed out  at  2018-08-20T12:55:48.023-04:00[US/Eastern]., errorContext[NS: cps-eventhub.servicebus.windows.net, PATH: pms-events, REFERENCE_ID: 0ccccadf60484bf8afceb9f5dc799303_G0, LINK_CREDIT: 48]
	at com.microsoft.azure.servicebus.MessageSender.throwSenderTimeout(MessageSender.java:787)
	at com.microsoft.azure.servicebus.MessageSender.access$1700(MessageSender.java:61)
	at com.microsoft.azure.servicebus.MessageSender$SendTimeout.run(MessageSender.java:895)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
`

## Versions  
- OS platform and version: Linux 4.1.12-124.14.1.el6uek.x86_64
- Maven package version or commit ID: azure-eventhubs-0.14.4

**Comment by SreeramGarlapati** [comment]
@JRiggenbach 
- errorContext (entitydetails, timestamp, linkCredit and referenceId) would help - if you file a support ticket with Microsoft during an outage..
- cause on the timeoutexception & enabling warn level logs should definitely help to get more insights in this case.

[am guessing - this issue was a way for asking a question and hence closing it after answering. please reopen as per need.]
