### ISSUE TITLE
[Question] When EventProcessor receive multiple events once

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#398]
`IEventProcessor` has method `onEvents(PartitionContext context, Iterable<EventData> events)`. In my experiment, I always receive one message on each method call. This means `events` has size `1`. I got 2 questions here:

1. When will we get multiple events on each method call? Does that mean we should send events in one batch?
2. Do we have control of `events` size?

**Comment by JamesBirdsall** [comment]
You have control of the maximum number of events in a batch, via EventProcessorOptions, but not the minimum size.

AMQP is a streaming protocol. The receiving client tells the service how many events it can buffer, and the service delivers events to the client as they become available. The client places those events in a buffer, and when the application makes a receive call, it gives events to the application from the buffer. The only time a receive call blocks is if there are no events in the buffer, in which case it waits up to the specified timeout. Otherwise, it takes as many as are in the buffer, or the maximum specified by the application, whichever is less.

If you are getting only one event per batch, that is normally the sign of a healthy application which can consume messages faster than they are produced.
