### ISSUE TITLE
EventProcessorHost#unregisterEventProcessor takes a long time

### ISSUE THREAD

**Issue by kdpak** [Azure/azure-event-hubs-java#406]
## Actual Behavior
1. On unregistering event processor host, the completion of the future takes 1-3 minutes. Is this expected? If so, is there any advice on how to improve on this time? Also, does the completion time depend on some other factor? e.g number of partitions, number of events coming in.

## Expected Behavior
1. To improve on the speed of the shutdown process or at least understand an upper bound to wait on before the process is automatically killed.

## Versions  
- Maven package version or commit ID: 2.0.1 of EPH / 1.2.1 of Event Hub

**Comment by JamesBirdsall** [comment]
When shutting down, an EventProcessorHost instance has to stop the receive pumps for all the partitions is owns. The current implementation of the receive pump in the underlying client waits for the current receive call to finish, whether by getting an event or by timeout, before it stops. Therefore, the time taken to unregister is affected by two factors: event traffic on the partitions owned, and the receive timeout setting. If traffic is high, the shutdown will be quick; if there is no traffic at all, the upper bound is the receive timeout. Since the individual partitions are shut down in parallel, the number of partitions owned has minimal or no effect.

Normally the shutdown path is not time-critical, so we have stuck with this simple, straightforward design. We have had this question a few times, but so far everyone has been satisfied once they understand why they see the delay. If you have a scenario where the shutdown time matters, please let us know!

**Comment by kdpak** [comment]
Fair enough James, thanks for the informative answer. Do you mind pointing me to where/what the timeout is?

**Comment by JamesBirdsall** [comment]
The default receive timeout is one minute. You can change that with EventProcessorOptions:
* call EventProcessorOptions.getDefaultOptions() to get an options instance set up with the defaults
* call setReceiveTimeout() on the options instance to change the timeout
* pass the options instance when you call registerEventProcessor()/registerEventProcessorFactory() on your EventProcessorHost instance to start processing
