### ISSUE TITLE
What are other ways to maintain checkpoints?

### ISSUE THREAD

**Issue by nikesh-dev** [Azure/azure-event-hubs-java#438]
We have 3 apps processing data from eventHub, and each app has 4 partitions associated with max batch fetch size of 100 . We perform average of 21 million fetches from event hub. i.e., 8.25 trans/second. 
Since checkpointing is also done after every fetch, we are experiencing high storage account I/O operations cost.

<a href="http://tinypic.com?ref=vnds02" target="_blank"><img src="http://i63.tinypic.com/vnds02.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Can you suggest some better ways of peforming checkpointing:
1) Is it better to maintain delay between consecutive check pointing?
2) Is it feasible to perform local check pointing? Do you foreseen any challenges? 

Please share your ideas on this. Thanks

**Comment by JamesBirdsall** [comment]
How often you should checkpoint depends on your application's ability to tolerate reprocessing events that were already processed. It is never possible to completely eliminate the possibility of reprocessing -- even if you checkpoint after every event, your application could crash between finishing the processing and making the checkpoint -- but checkpointing more often reduces the maximum number of events that you may reprocess. However, checkpointing is a slow operation, impacting application performance, and it also costs money. So our general recommendation is to determine how many events you can reprocess without causing trouble and then checkpoint as infrequently as possible based on that.

One of the main features of Event Processor Host is being able to have multiple cooperating host instances operating on the same consumer group which divide up the partitions of the event hub between them. One of the assumptions required to implement that feature is that leases and checkpoints exist in some shared store which all cooperating host instances can access. For example: suppose partition 0 is being handled by host instance "A", and then "A" is taken down for maintenance. Host instance "B" takes ownership of partition 0, but "B" needs to have access to the last checkpoint written for partition 0 while it was still on "A". Later on, "A" is returned to service, and partition 0 migrates back to "A", which needs to have access to the checkpoints written by "B". In this sort of multi-machine scenario, checkpoints on storage local to a machine don't work. If you design your application so that it will only ever have one host instance which will always run on the same machine, you can do it, but you have given up the resilience and scalability that Event Processor Host normally provides.

**Comment by JamesBirdsall** [comment]
If you have any additional questions, please reopen and we can continue the discussion.
