### ISSUE TITLE
EPH library does not expose metadata about event hub partitions

### ISSUE THREAD

**Issue by agnusMagnus** [Azure/azure-event-hubs-java#456]
EPH library does not expose metadata about event hub partitions, in particular the last offset. The information is available on the REST API and described at https://docs.microsoft.com/en-us/rest/api/eventhub/list-partition-runtime-metadata

The information is very useful for a client to know what is the range of valid offsets and when it was last set. If the client submits an invalid offset, the processor would err and shutdown.

## Versions  
- com.microsoft.azure:azure-eventhubs-eph:2.1.0

**Comment by agnusMagnus** [comment]
maybe the information should be passed in 
`    // OnOpen is called when a new event processor instance is created by the host.
    @Override
    public void onOpen(PartitionContext context) throws Exception {
    }`

but the context.getRuntimeInformation() is empty

**Comment by JamesBirdsall** [comment]
The information exposed by context.getRuntimeInformation is piggybacked on the messages themselves. It is only populated after you have received at least one message for a partition.

**Comment by agnusMagnus** [comment]
Is there a way to know before submitting an offset, what the last valid offset is ?

**Comment by JamesBirdsall** [comment]
The only way to know the highest valid offset is to query the service in some way, because only the service has that information. Alternatively, if you simply want to start receiving from the highest valid offset, don't use checkpoints and set the initial position provider to EndOfStreamInitialPositionProvider.

This client is now legacy and in maintenance mode. We will not be adding new features. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs
