### ISSUE TITLE
Are there any guarantees about single-threaded access to IEventProcessor callbacks?

### ISSUE THREAD

**Issue by adriancole** [Azure/azure-event-hubs-java#52]
## Actual Behavior
Right now, there's no documentation about whether instances of `IEventProcessor` are invoked in a single thread or not. This means that callers need to handle shared state defensively, which is particularly difficult to test as code involved is in package protected signed jars.

## Expected Behavior
Ideally, I'd like to see the creation of an IEventProcessor and all callbacks on a single-thread. This makes the programming model very simple, especially if batching is done. Otherwise, I'd at least like to see some documentation on the interface of the factor or the processor about how someone should handle concurrency.

## Versions  
0.10.0 event hubs. Here's the code I can't quite understand  https://github.com/Azure/azure-event-hubs-java/blob/e6413d059471d75224a62df89251c5dfd331f5e2/azure-eventhubs-eph/src/main/java/com/microsoft/azure/eventprocessorhost/PartitionPump.java#L148

Pull request in mention, which can be dramatically simplified if single-threaded call backs are made used https://github.com/openzipkin/zipkin-azure/pull/17

**Comment by JamesBirdsall** [comment]
To answer the question: OnOpen/OnEvents/OnClose are single-threaded in the sense that they are guaranteed to not be called while another call is in progress. OnEvents is literally single-threaded because it runs in the message pump thread owned by the underlying event hub client; that is an implementation detail which could change, but the guarantee will not change. OnError is not guaranteed to not be concurrent because that could potentially cause a deadlock.

I agree that this should be documented and will get it into the README. I will also try to make the comment clearer.

Thanks for bringing this up!

**Comment by adriancole** [comment]
thanks, so we don't need to worry about mutual exclusion, since callbacks
are one-at-a-time. However, we still need to worry about visibility, as
different threads may invoke the callbacks (which means writes still need
to flush).

this helps!

**Comment by jtaubensee** [comment]
Closing, based on #52
